### ISSUE TITLE
Call to undefined function getState() in version 1.1.3

### ISSUE THREAD

**Issue by kokoshneta** [sweebee/filament-char-counter#11]
The recent fix to #9 appears to have broken this plugin completely for me, and I’m not sure if it’s a simple typo or if my environment is missing something.

The fix involved [this commit for textareas](https://github.com/sweebee/filament-char-counter/commit/38e6db10730fd383c0d1e76bbcd8ec47996adb0b); previously the view had this:

```blade
{{ mb_strlen($getState()) }}
```

– and now it has this:

```blade
{{ mb_strlen($getState() ? getState() : '') }}
```

– with `getState()` rather than `$getState()` in the true branch of the ternary.

I haven’t used the plugin with a text input field, but the same presumably holds true there, since the [current commit](https://github.com/sweebee/filament-char-counter/commit/5111fe41e566f0b789c3a6c2d71d18a5a447ef1a) for those now has this:

```blade
{{ mb_strlen(getState()? $getState()) : '' }}
```

– so still with `getState()`, but in a different position (condition instead of true branch).

But what exactly is `getState()`, as opposed to Filament’s `$getState()`? In my app, the function is not defined, and I don’t know if the initial `$` was just left out by accident, or if there is actually supposed to be a `getState()` function defined somewhere.

Adding a `$` back in fixes the issue, so I’m assuming it’s just a typo?

**Comment by sweebee** [comment]
thanks, yea a typo and I didn't test it. Could you test 1.1.4?

**Comment by kokoshneta** [comment]
Well, that was fast! Works perfectly now in 1.1.4!
