### ISSUE TITLE
Method Filament\Forms\Components\TextInput::characterLimit does not exist.

### ISSUE THREAD

**Issue by GianmarcoVarroneDev** [sweebee/filament-char-counter#3]
After following the documentation and installing the package, whenever i call characterLimit() i get the error in the title, while if I call maxLength() nothing displays on the input but only the maxLength validation rule from filament is applied. Where should i look to make this work?

**Comment by Harverbo** [comment]
@GianmarcoVarroneDev you should use Wiebenieuwenhuis\FilamentCharCounter\TextInput instead of Filament\Forms\Components\TextInput.
